---
- block:

    - name: Gather facts
      setup:
          
    - name: Check if kubernetes already installed on Master
      stat: path=/etc/kubernetes/admin.conf
      register: kube_installed

    - name: install kubernetes
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: kube_installed
      when: not kube_installed.stat.exists
      
    - name: create .kube directory
      file:
        path: "{{ ansible_env.HOME }}/.kube"
        state: directory

    - name: copy kubernetes config
      shell: cp /etc/kubernetes/admin.conf "{{ ansible_env.HOME }}/.kube/config"
      when: kube_installed.changed

    - name: get token
      shell: kubeadm token list | awk 'NR>1 { print $1 }'
      register: token
      changed_when: false
  
    - name: copy flannel deployment
      copy:
        src: ./files/deploy/kube-flannel.yml
        dest: ~/
      changed_when: false
  
    - name: Check if flannel already installed
      shell: kubectl get ds -n kube-system | grep kube-flannel-ds
      register: flannel_status
      changed_when: false
      ignore_errors: true
        
    - name: Install flannel
      shell: kubectl apply -f "/root/deploy/kube-flannel.yml"
      when: flannel_status.stdout == "" 
        
  become: yes