---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: init
spec:
  capacity:
    storage: 5G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kube-nfs.init
  mountOptions:
    - nfsvers=4.1
  nfs:
    path: /share/init
    server: 10.0.30.80