- name: Create NFS PVs
  hosts: kube-nfs
  connection: local
  environment:
    KUBECONFIG: "{{ lookup('env','PWD') }}/admin.conf"
      
  tasks: 
    - template:
        src: templates/nfs-pvs.j2
        dest: nfs-pvs.yml