## create a virtual machine on ESXI host


- name: include vsphere details
  include_vars: vsphere.yaml

- debug:
        msg: "{{ name }} "

#- debug:
#        msg: "{{ vm }} "

- name: include vm details
  include_vars: vm.yaml

- name: Create a VM folder on given datacenter
  vcenter_folder:
    hostname:   '{{ vsphere.ip }}'
    username:   '{{ vsphere.user}}'
    password:   '{{ vsphere.passw}}'
    datacenter: '{{ vsphere.dc}}'
    folder_name: '{{ vsphere.folder}}'
    folder_type: vm
    state: present
    validate_certs: no
  register: vm_folder_creation_result

- name: Clone a VM from Template and customize
  delegate_to: localhost
  connection: local
  vmware_guest:

    hostname:   '{{ vsphere.ip }}'
    username:   '{{ vsphere.user}}'
    password:   '{{ vsphere.passw}}'
    datacenter: '{{ vsphere.dc}}'
    folder:     '{{ vsphere.folder}}'
    validate_certs: no
    name: "{{ name }}"
    state: poweredon
    template: "{{ vm[name].template }}"
    networks:
      - name: "{{ vm[name].network }}"
        ip: "{{ vm[name].ip }}"
        netmask: "{{ vm[name].netmask }}"
        gateway: "{{ vm[name].gateway }}"
        domain: "{{ vm[name].domain }}"
        dns_servers:
          - "{{ vm[name].dns }}"
        type: static
        wait_for_ip_address: yes
    customization:
      dns_servers:
      - "{{ vm[name].dns }}"
