- name: Install Kubernetes on Master nodes
  hosts: kube-masters
  gather_facts: yes
  become: yes
  tasks:
      
    - name: install dashboard
#      shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
      shell: kubectl apply -f ~/deploy/kubernetes-dashboard.yml

    - name: install dashboard user
      shell: kubectl apply -f ~/deploy/kubernetes-dashboard-user.yml

    - name: get token for dashboard
      shell: kubectl describe secret -n kube-system $(kubectl get secret -n kube-system | grep admin-user | awk '{print $1}')
      register: dashboard_token

    - name: copy dashboard token to localhost
      become: no
      local_action: copy content={{ dashboard_token }} dest=./dashboard_token.txt
   
# helm on machine running ansible is required
- name: install default pods
  hosts: localhost
  connection: local
  environment:
    KUBECONFIG: "{{ lookup('env','PWD') }}/admin.conf"
         
  tasks:

    - name: remove master from knownhosts file
      shell: ssh-keygen -R "{{ hostvars['kube-master1']['ansible_host'] }}" -f ~/.ssh/known_hosts
      
    - name: add master to knownhosts file
      shell: echo "kubernetes ecdsa-sha2-nistp256 {{ hostvars['kube-master1']['ansible_ssh_host_key_ecdsa_public'] }}"  >> ~/.ssh/known_hosts

    - name: set kubernetes server to https://kubernetes:6443
      shell: kubectl config set-cluster kubernetes --server=https://kubernetes:6443

    - name: helm init
      shell: helm init
      ignore_errors: yes
    
    - name: create tiller access
      shell: kubectl create serviceaccount --namespace kube-system tiller
             && kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
      ignore_errors: yes

    - name: patch tiller
      shell: kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'
      ignore_errors: yes
     
    - name: wait for tiller ready
      shell: helm status
      ignore_errors: yes
      register: tiller_state
      until: "tiller_state.stderr != 'Error: could not find a ready tiller pod'"
      retries: 30
      timeout: 10
      
    - name: install ingress controller
      shell: helm install stable/nginx-ingress --namespace kube-system --set rbac.create=true
      ignore_errors: yes
      retries: 30
      timeout: 10

    
