## create a kubernetes cluster on VMware ESXi
##
- name: Create virtual machines
  hosts: kubernetes
  gather_facts: no
  vars_files:
    - vars/vsphere.yml
    
  pre_tasks:
      - include_role: name=esxi-folder
        when: inventory_hostname in groups.masters
        
      - include_role: name=esxi-vm
      
  roles:
    - ntp      
    - docker
    - kubernetes

## setup master
##
- name: Setup master
  hosts: masters
  gather_facts: no
  roles:
      - kube-master
        
## setup workers
- name: Setup workers
  hosts: workers
  gather_facts: no
  roles:
      - kube-worker
      
# helm on machine running ansible is required
# setup localhost for kubctl & helm
- name: Setup localhost for kubectl usage
  hosts: localhost
  connection: local
  environment:
    KUBECONFIG: "{{ lookup('env','PWD') }}/admin.conf"
  tasks:
     - include_role: name=kubectl-config 
     - include_role: name=tiller
         
     # - name: wait for all nodes to get ready
     #   shell: kubectl get nodes | grep "NotReady"
     #   ignore_errors: yes
     #   register: node_state
     #   until: node_state.stdout == ""
     #   retries: 30
     #   delay: 10   
     #   when: flannel_status.stdout == "" 
     
      # - include_role:
      #     name: kube-dashboard
      #   when: inventory_hostname in groups.masters