---
all:
  vars:
    ansible_user: tutorial        
  children:
    dev:
      hosts:
        localhost:
          ansible_host: 127.0.0.1
          ansible_connection: local
          ansible_python_interpreter: /usr/local/bin/python
    kubernetes:
        vars:
            ansible_python_interpreter: /usr/bin/python
            host_network:  dc30.kube
            host_domain:   dc.decromlab.nl
            host_dns:      10.0.30.1
            host_gateway:  10.0.30.1
            host_netmask:  255.255.255.0
            ntp_timezone:  Europe/Amsterdam
            ntp_servers:   [10.0.30.1]
            dockerrepo:    dockerrepo:5000
        children:
            masters:
                hosts:
                  kube-master1:
                    ansible_host: 192.168.178.70
                    host_ip:      10.0.30.70
            workers:
                hosts:
                  kube-worker1:
                    ansible_host: 192.168.178.71
                    host_ip:      10.0.30.71
                  kube-worker2:
                    ansible_host: 192.168.178.72
                    host_ip:      10.0.30.72
                  kube-worker3:
                    ansible_host: 192.168.178.73
                    host_ip:      10.0.30.73
                    

