  - name: set timezone
    shell: timedatectl set-timezone Europe/Amsterdam

  - name: Install NTP
    yum: name=ntp state=installed

  - name: Copy over the NTP configuration
    template: src=./templates/ntp.conf dest=/etc/ntp.conf

  - name: Make sure NTP is stopped
    service: name=ntpd state=stopped enabled=yes

  - name: Make sure NTP is started up
    service: name=ntpd state=started enabled=yes
